// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Neon requires a direct (non-pooled) connection for schema migrations.
    url: process.env["MJWEDDING_POSTGRES_URL_NON_POOLING"],
  },
});
